### ISSUE TITLE
Change the name of the default rake task

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/scraper_test#7]
# Problem

The rake task currently defaults to being called `:test`, but this conflicts with `Rake::TestTask`.

# Proposed solution

Change the name of the rake task this library produces. I think calling it `:scraper_test` would probably be sensible.

**Comment by tmtmtmtm** [comment]
Maybe `:test_data` (or `:data_test`), to emphasise that it's running the data-driven tests?

**Comment by chrismytton** [comment]
Ah yep, I like `:test_data`. I _think_ perhaps it would be more "standard" (FSVO) to call it `test:data` (with a `:` instead of an `_`)?

**Comment by tmtmtmtm** [comment]
Works for me!
